name: Build and Release OnePlus 13R Bright-Star Kernel

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - none
          - Pre-release
          - Release
        default: none
      manifest:
        description: 'Kernel manifest'
        required: true
        type: choice
        options:
          - OOS14
          - OOS15
          - FAST_BUILD_OOS15
        default: OOS15
      ksun_branch:
        description: 'KernelSU Next branch/commit'
        required: true
        type: string
        default: next
      optimize_level:
        description: 'Optimization level'
        required: true
        type: choice
        options: [O2, O3]
        default: O2
      kernel_version:
        description: 'Kernel version (e.g., 1.5.12)'
        required: true
        type: string
        default: '1.5.12'
      kernel_uname:
        description: 'Kernel uname'
        type: string
        default: 'Bright-Star'
      susfs_branch_or_commit:
        description: 'SUSFS branch/commit (optional)'
        type: string
        default: ''

jobs:
  set-op-model:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            configs/
          sparse-checkout-cone-mode: false

      - name: Setup Build Matrix
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          configs=()
          while IFS= read -r -d '' file; do
            model=$(basename "$file" .json)
            configs+=("$model")
          done < <(find configs/ -name "*.json" -print0)

          [[ ${#configs[@]} -eq 0 ]] && { echo "❌ No config files found!"; exit 1; }
          
          echo "Found configs: ${configs[*]}"
          
          matrix=$(jq -cn --args '$ARGS.positional' "${configs[@]}" | \
            jq '{include: map({model: ., config: ("configs/" + . + ".json")})}')
          
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$matrix" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: Build Kernel & Modules
    needs: set-op-model
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-op-model.outputs.matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Kernel & Modules
        uses: ./.github/actions/kernel-action
        with:
          op_config_json: ${{ toJSON(matrix) }}
          ksun_branch: ${{ inputs.ksun_branch }}
          susfs_commit_hash_or_branch: ${{ inputs.susfs_branch_or_commit }}
          optimize_level: ${{ inputs.optimize_level }}
          kernel_uname: ${{ inputs.kernel_uname }}
          manifest: ${{ inputs.manifest }}

  trigger-release:
    needs: build-kernel
    runs-on: ubuntu-latest
    if: ${{ inputs.release_type != 'none' }}
    timeout-minutes: 30
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Wireless Firmware
        run: |
          set -euo pipefail
          DOWNLOAD_DIR="./downloaded-artifacts/wireless-firmware"
          mkdir -p "$DOWNLOAD_DIR"
          
          LATEST_TAG=$(gh api repos/terminal-beginner/Nethunter-Wireless-Firmware/releases/latest --jq '.tag_name' || true)
          [[ -z "$LATEST_TAG" ]] && { echo "::warning::No firmware release found"; exit 0; }
          
          ASSET="Nethunter-Wireless-Firmware-${LATEST_TAG}.zip"
          echo "📡 Downloading $ASSET..."
          gh release download "$LATEST_TAG" --repo terminal-beginner/Nethunter-Wireless-Firmware --pattern "$ASSET" --dir "$DOWNLOAD_DIR" --clobber

      - name: Generate Tag
        run: |
          set -euo pipefail
          BASE="v${{ inputs.kernel_version }}"
          LATEST=$(gh api repos/${{ github.repository }}/tags --jq '.[0].name' || echo "")
          
          if [[ "$LATEST" =~ ^${BASE}-r[0-9]+$ ]]; then
            SUFFIX=$(echo "$LATEST" | grep -oE 'r[0-9]+$' | grep -oE '[0-9]+')
            NEW_SUFFIX=$((SUFFIX + 1))
          else
            NEW_SUFFIX=1
          fi
          
          NEW_TAG="${BASE}-r${NEW_SUFFIX}"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Generate Release Notes
        run: |
          set -euo pipefail
          OS_VER=$(echo "${{ inputs.manifest }}" | sed 's/FAST_BUILD_//' | tr '[:lower:]' '[:upper:]')
          
          cat > release_notes.md <<EOF
          ## Bright-Star Kernel for OnePlus 13R - $OS_VER
            
          **Manifest:** ${{ inputs.manifest }}  
          **Optimization:** ${{ inputs.optimize_level }}  
          **KernelSU Next:** ${{ inputs.ksun_branch }}  
          **SUSFS:** v${{ inputs.kernel_version }}
          
          ### Downloads
          - **Kernel ZIP**: Flashable via recovery
          - **Modules ZIP**: Unified kernel modules
          - **Boot IMG**: Pre-patched boot image
          
          ### Features
          - ✓ KernelSU-Next / WildKSU Manager Support
          - ✓ SUSFS v${{ inputs.kernel_version }} + Magic Mount
          - ✓ NetHunter Support (WiFi injection, etc.)
          - ✓ Baseband Guard (BBG)
          - ✓ BBR v1 TCP Congestion
          - ✓ MemKernel driver
          - ✓ IP Set Support
          
          ### Device Builds
          EOF
          
          echo "| Model | Kernel Version |" >> release_notes.md
          echo "|-------|----------------|" >> release_notes.md
          find downloaded-artifacts -name "*.txt" -type f | while read -f; do
            [[ -n "$f" ]] || continue
            model=$(basename "$f" .txt)
            version=$(cat "$f")
            printf "| %-12s | %-16s |\n" "$model" "$version" >> release_notes.md
          done

      - name: Create Release
        run: |
          set -euo pipefail
          OS_VER=$(echo "${{ inputs.manifest }}" | sed 's/FAST_BUILD_//' | tr '[:lower:]' '[:upper:]')
          TITLE="Bright-Star Kernel (${{ inputs.kernel_uname }}) - $OS_VER"
          
          [[ "${{ inputs.release_type }}" == "Pre-release" ]] && IS_PRERELEASE="--prerelease" || IS_PRERELEASE=""
          
          gh release create "${{ env.NEW_TAG }}" \
            --repo "${{ github.repository }}" \
            --title "$TITLE" \
            --notes-file release_notes.md \
            $IS_PRERELEASE

      - name: Upload Assets
        run: |
          set -euo pipefail
          for file in ./downloaded-artifacts/**/*.{zip,img}; do
            [[ -f "$file" ]] || continue
            echo "⬆️ Uploading $(basename "$file")..."
            gh release upload "${{ env.NEW_TAG }}" "$file" --clobber
          done
